export const CREATE_COMPUTERS = 'CREATE_COMPUTERS';

export const USE_COMPUTER = 'USE_COMPUTER';
export const LEAVE_COMPUTER = 'LEAVE_COMPUTER';

export const GET_COMPUTER_STARTED = 'GET_COMPUTER_STARTED';
export const GET_COMPUTER_COMPLETED = 'GET_COMPUTER_COMPLETED';